from django.urls import include, path

from . import (
    acessos_views,
    comunicados_views,
    repositorio_views,
    rota_views,
    tradehub_views,
    vertical_views,
    views,
)

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.StaffLoginView.as_view(), name="login"),
    path("logout/", views.StaffLogoutView.as_view(), name="logout"),
    path("perfil/", views.meu_perfil, name="meu_perfil"),
    path("comunicados/", comunicados_views.comunicados_lista, name="comunicados_lista"),
    path(
        "comunicados/pendente/",
        comunicados_views.comunicado_pendente,
        name="comunicado_pendente",
    ),
    path(
        "comunicados/gerir/",
        comunicados_views.comunicados_gerir,
        name="comunicados_gerir",
    ),
    path(
        "comunicados/gerir/novo/",
        comunicados_views.comunicado_gerir_form,
        name="comunicado_novo",
    ),
    path(
        "comunicados/gerir/<int:pk>/",
        comunicados_views.comunicado_gerir_form,
        name="comunicado_editar",
    ),
    path(
        "comunicados/<int:pk>/",
        comunicados_views.comunicado_detalhe,
        name="comunicado_detalhe",
    ),
    path("senha/trocar/", acessos_views.senha_trocar, name="senha_trocar"),
    path("senha/sessoes/encerrar/", acessos_views.logout_todas_sessoes, name="logout_todas_sessoes"),
    path("acessos/", acessos_views.acessos_lista, name="acessos"),
    path("acessos/auditoria/", acessos_views.acessos_auditoria, name="acessos_auditoria"),
    path("acessos/<int:pk>/resetar/", acessos_views.acesso_resetar, name="acesso_resetar"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("fila/", views.fila, name="fila"),
    path("tickets/novo/", views.ticket_criar, name="ticket_criar"),
    path("tickets/<str:protocolo>/responder/", views.ticket_responder, name="ticket_responder"),
    path("tickets/<str:protocolo>/mascaras.json", views.ticket_mascaras_json, name="ticket_mascaras_json"),
    path("tickets/<str:protocolo>/enviar-mascara/", views.ticket_enviar_mascara_api, name="ticket_enviar_mascara_api"),
    path("tickets/<str:protocolo>/", views.ticket_detalhe, name="ticket_detalhe"),
    path("campos-resposta/", views.config_resposta_lista, name="config_resposta_lista"),
    path("campos-resposta/<str:tipo>/", views.config_resposta_editar, name="config_resposta_editar"),
    path("abrir/", views.portal_inicio, name="portal_inicio"),
    path("abrir/demanda/", views.abrir_demanda, name="abrir_demanda"),
    path("tradehub/", tradehub_views.tradehub_inicio, name="tradehub"),
    path("tradehub/arquivo/<path:rel>", tradehub_views.tradehub_arquivo, name="tradehub_arquivo"),
    path("tradehub/<slug:slug>/", tradehub_views.tradehub_secao, name="tradehub_secao"),
    path("tradehub/<slug:slug>/<path:pasta>/", tradehub_views.tradehub_secao, name="tradehub_pasta"),
    path("repositorio/", repositorio_views.repositorio_lista, name="repositorio_lista"),
    path("repositorio/gerir/", repositorio_views.repositorio_gerir_lista, name="repositorio_gerir_lista"),
    path("repositorio/gerir/novo/", repositorio_views.repositorio_gerir_form, name="repositorio_gerir_novo"),
    path(
        "repositorio/gerir/<int:pk>/",
        repositorio_views.repositorio_gerir_form,
        name="repositorio_gerir_editar",
    ),
    path(
        "repositorio/gerir/<int:processo_pk>/anexo/",
        repositorio_views.repositorio_anexo_form,
        name="repositorio_anexo_novo",
    ),
    path(
        "repositorio/gerir/<int:processo_pk>/anexo/<int:pk>/",
        repositorio_views.repositorio_anexo_form,
        name="repositorio_anexo_editar",
    ),
    path(
        "repositorio/gerir/anexo/<int:pk>/excluir/",
        repositorio_views.repositorio_anexo_excluir,
        name="repositorio_anexo_excluir",
    ),
    path(
        "repositorio/gerir/<int:processo_pk>/link/",
        repositorio_views.repositorio_link_form,
        name="repositorio_link_novo",
    ),
    path(
        "repositorio/gerir/<int:processo_pk>/link/<int:pk>/",
        repositorio_views.repositorio_link_form,
        name="repositorio_link_editar",
    ),
    path(
        "repositorio/gerir/link/<int:pk>/excluir/",
        repositorio_views.repositorio_link_excluir,
        name="repositorio_link_excluir",
    ),
    path("repositorio/<slug:slug>/", repositorio_views.repositorio_detalhe, name="repositorio_detalhe"),
    path("abrir/formulario/", views.abrir_demanda_form, name="abrir_demanda_form"),
    path("abrir/inicio/", views.portal_parceiro, name="portal_parceiro"),
    path("abrir/contato/", views.portal_contato, name="portal_contato"),
    path("abrir/rota/", rota_views.rota_portal, name="rota_portal"),
    path("abrir/rota/api/hoje/", rota_views.rota_api_hoje, name="rota_api_hoje"),
    path("abrir/rota/api/localidades/ufs/", rota_views.rota_api_ufs, name="rota_api_ufs"),
    path(
        "abrir/rota/api/localidades/cidades/",
        rota_views.rota_api_cidades,
        name="rota_api_cidades",
    ),
    path(
        "abrir/rota/api/localidades/bairros/",
        rota_views.rota_api_bairros,
        name="rota_api_bairros",
    ),
    path(
        "abrir/rota/api/dfv/resumo/",
        rota_views.rota_api_dfv_resumo,
        name="rota_api_dfv_resumo",
    ),
    path(
        "abrir/rota/api/planejamento/validar/",
        rota_views.rota_api_planejamento_validar,
        name="rota_api_planejamento_validar",
    ),
    path("abrir/rota/api/agendas/", rota_views.rota_api_agendas, name="rota_api_agendas"),
    path("abrir/rota/api/checkin/", rota_views.rota_api_checkin, name="rota_api_checkin"),
    path("abrir/vertical/", vertical_views.vertical_portal, name="vertical_portal"),
    path(
        "abrir/vertical/api/dashboard/",
        vertical_views.vertical_api_dashboard,
        name="vertical_api_dashboard",
    ),
    path(
        "abrir/vertical/api/solicitacoes/",
        vertical_views.vertical_api_solicitacoes,
        name="vertical_api_solicitacoes",
    ),
    path(
        "abrir/vertical/api/solicitacoes/<int:pk>/",
        vertical_views.vertical_api_solicitacao,
        name="vertical_api_solicitacao",
    ),
    path(
        "abrir/vertical/api/solicitacoes/<int:pk>/resend/",
        vertical_views.vertical_api_solicitacao_resend,
        name="vertical_api_solicitacao_resend",
    ),
    path(
        "abrir/vertical/api/viacep/<str:cep>/",
        vertical_views.vertical_api_viacep,
        name="vertical_api_viacep",
    ),
    path(
        "abrir/vertical/api/nominatim/",
        vertical_views.vertical_api_nominatim,
        name="vertical_api_nominatim",
    ),
    path(
        "abrir/vertical/api/config/",
        vertical_views.vertical_api_config,
        name="vertical_api_config",
    ),
    path(
        "abrir/vertical/api/usuarios/",
        vertical_views.vertical_api_usuarios,
        name="vertical_api_usuarios",
    ),
    path("abrir/minhas/", views.minhas_demandas, name="minhas_demandas"),
    path("abrir/sair/", views.portal_sair, name="portal_sair"),
    path("consulta/", views.consulta_busca, name="consulta_busca"),
    path("consulta/<str:protocolo>/", views.consulta_protocolo, name="consulta_protocolo"),
    path("consultas/", include("tickets.consultas.urls")),
    path("parceiros/", views.parceiros_lista, name="parceiros"),
    path("especialistas/", views.especialistas_lista, name="especialistas"),
    path("especialistas/novo/", views.especialista_form, name="especialista_novo"),
    path("especialistas/<int:pk>/excluir/", views.especialista_excluir, name="especialista_excluir"),
    path("especialistas/<int:pk>/", views.especialista_form, name="especialista_editar"),
    path("parceiros/novo/", views.parceiro_form, name="parceiro_novo"),
    path("parceiros/<int:pk>/", views.parceiro_form, name="parceiro_editar"),
    path("parceiros/<int:pk>/inativar/", views.parceiro_inativar, name="parceiro_inativar"),
    path("parceiros/<int:pk>/reativar/", views.parceiro_reativar, name="parceiro_reativar"),
    path("parceiros/<int:pk>/gerar-senha/", acessos_views.acesso_gerar_parceiro, name="acesso_gerar_parceiro"),
    path("parceiros/<int:pk>/excluir/", views.parceiro_excluir, name="parceiro_excluir"),
    path("contatos/<int:pk>/toggle/", views.contato_toggle, name="contato_toggle"),
    path("contatos/<int:pk>/excluir/", views.contato_excluir, name="contato_excluir"),
    path("contatos/<int:pk>/token/", views.contato_gerar_token, name="contato_gerar_token"),
    path("mascaras/", views.mascaras_lista, name="mascaras"),
    path("mascaras/nova/", views.mascara_form, name="mascara_nova"),
    path("mascaras/<int:pk>/", views.mascara_form, name="mascara_editar"),
]
