# Generated by Django 5.2.17 on 2026-08-20 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0013_isolar_auth_do_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestaoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=80, unique=True)),
                ('valor', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Configuração de gestão',
                'verbose_name_plural': 'Configurações de gestão',
            },
        ),
        migrations.CreateModel(
            name='CadastroTerceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nome_terceiro', models.CharField(blank=True, max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('razao_social', models.CharField(blank=True, db_index=True, max_length=200)),
                ('vinculo', models.CharField(blank=True, max_length=50)),
                ('cargo_funcao', models.CharField(blank=True, max_length=100)),
                ('situacao_empresa', models.CharField(blank=True, max_length=50)),
                ('situacao_funcional', models.CharField(blank=True, max_length=80)),
                ('situacao_contrato', models.CharField(blank=True, max_length=50)),
                ('data_alocacao', models.DateField(blank=True, null=True)),
                ('data_desalocacao', models.DateField(blank=True, null=True)),
                ('data_inativacao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=False)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceiros', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Terceiro (Sysmap)',
                'verbose_name_plural': 'Terceiros (Sysmap)',
                'ordering': ['nome_terceiro', 'chave_acesso'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoChurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateField(db_index=True)),
                ('pdv_nome', models.CharField(max_length=100)),
                ('anomes_gross', models.IntegerField()),
                ('gross', models.IntegerField()),
                ('churn', models.IntegerField()),
                ('taxa_churn', models.FloatField()),
                ('remanescentes', models.IntegerField()),
                ('bonus_m10', models.FloatField()),
                ('mensagem', models.TextField(blank=True)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_churn', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Histórico de churn',
                'verbose_name_plural': 'Históricos de churn',
                'ordering': ['pdv_nome', '-anomes_gross'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoOSAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_processamento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('descricao_pdv', models.CharField(max_length=150)),
                ('status', models.CharField(default='Ok', max_length=50)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('realizado_vl', models.FloatField(blank=True, null=True)),
                ('atingimento_vl', models.FloatField(blank=True, null=True)),
                ('realizado_gross', models.IntegerField(blank=True, null=True)),
                ('atingimento_gross', models.FloatField(blank=True, null=True)),
                ('comissao_total_projetada', models.FloatField(blank=True, null=True)),
                ('mensagem', models.TextField(blank=True)),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_osab', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Histórico OSAB',
                'verbose_name_plural': 'Históricos OSAB',
                'ordering': ['-data_processamento', 'descricao_pdv'],
            },
        ),
        migrations.CreateModel(
            name='LoteImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sysmap', 'Sysmap / Supply'), ('osab', 'OSAB'), ('fpd', 'FPD'), ('churn', 'Churn')], db_index=True, max_length=20)),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('ok', models.BooleanField(default=True)),
                ('erro', models.TextField(blank=True)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_gestao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de importação',
                'verbose_name_plural': 'Lotes de importação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioFPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdv_nome', models.CharField(max_length=150)),
                ('percentual', models.FloatField()),
                ('total_faturas', models.IntegerField()),
                ('total_abertas', models.IntegerField()),
                ('mensagem', models.TextField(blank=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_fpd', to='gestao.loteimportacao')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_fpd', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Relatório FPD',
                'verbose_name_plural': 'Relatórios FPD',
                'ordering': ['-percentual', 'pdv_nome'],
            },
        ),
        migrations.CreateModel(
            name='VendaOSAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(db_index=True, max_length=100, unique=True)),
                ('dt_ref', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('matricula_vendedor', models.CharField(blank=True, db_index=True, max_length=100)),
                ('nome_vendedor', models.CharField(blank=True, max_length=200)),
                ('pdv_nome', models.CharField(db_index=True, max_length=150)),
                ('data_abertura', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=200)),
                ('velocidade', models.CharField(blank=True, max_length=100)),
                ('meio_pagamento', models.CharField(blank=True, max_length=100)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_osab', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Venda OSAB',
                'verbose_name_plural': 'Vendas OSAB',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseCapilaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateField()),
                ('ano_referencia', models.IntegerField(db_index=True)),
                ('mes_referencia', models.IntegerField(db_index=True)),
                ('matricula_vendedor', models.CharField(db_index=True, max_length=100)),
                ('nome_vendedor', models.CharField(blank=True, max_length=200)),
                ('pdv_nome', models.CharField(db_index=True, max_length=150)),
                ('dias_sem_vender', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('ultima_venda', models.DateTimeField(blank=True, null=True)),
                ('sem_venda_osab', models.BooleanField(default=False)),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_capilaridade', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Análise de capilaridade',
                'verbose_name_plural': 'Análises de capilaridade',
                'ordering': ['pdv_nome', 'matricula_vendedor'],
                'indexes': [models.Index(fields=['ano_referencia', 'mes_referencia'], name='gestao_anal_ano_ref_17d9da_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoOSAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('meta_vl', models.IntegerField(default=0)),
                ('du_vl', models.FloatField(default=0)),
                ('meta_gross', models.IntegerField(default=0)),
                ('du_gross', models.FloatField(default=0)),
                ('pesos_diarios_vl', models.TextField(blank=True)),
                ('pesos_diarios_gross', models.TextField(blank=True)),
                ('comissao_500', models.IntegerField(default=0)),
                ('comissao_700', models.IntegerField(default=0)),
                ('comissao_1000', models.IntegerField(default=0)),
                ('tem_bonus', models.BooleanField(default=False)),
                ('comissao_bonus', models.IntegerField(default=0)),
                ('tem_bonus_m10', models.BooleanField(default=False)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_osab', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Configuração OSAB',
                'verbose_name_plural': 'Configurações OSAB',
                'constraints': [models.UniqueConstraint(fields=('parceiro', 'ano', 'mes'), name='uniq_config_osab_parceiro_periodo')],
            },
        ),
        migrations.CreateModel(
            name='GrossMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomes', models.IntegerField()),
                ('gross', models.IntegerField(default=0)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gross_mensal', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Gross mensal',
                'verbose_name_plural': 'Gross mensal',
                'constraints': [models.UniqueConstraint(fields=('parceiro', 'anomes'), name='uniq_gross_parceiro_anomes')],
            },
        ),
        migrations.CreateModel(
            name='MetaCapilaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('meta_vendedores', models.IntegerField(default=0)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_capilaridade', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Meta de capilaridade',
                'verbose_name_plural': 'Metas de capilaridade',
                'constraints': [models.UniqueConstraint(fields=('parceiro', 'ano', 'mes'), name='uniq_meta_cap_parceiro_periodo')],
            },
        ),
    ]
