# Generated by Django 5.2.17 on 2026-08-20 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_primeira_onda'),
        ('tickets', '0013_isolar_auth_do_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do destino')),
                ('jid', models.CharField(help_text='Número com DDI (ex.: 5531999999999) ou JID de grupo (…@g.us).', max_length=80, verbose_name='JID WhatsApp')),
                ('tipo', models.CharField(choices=[('individual', 'Número / contato'), ('grupo', 'Grupo WhatsApp')], default='individual', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('prioridade', models.PositiveIntegerField(default=100)),
                ('envio_osab', models.BooleanField(default=True, verbose_name='OSAB')),
                ('envio_capilaridade', models.BooleanField(default=True, verbose_name='Capilaridade')),
                ('envio_fpd', models.BooleanField(default=True, verbose_name='FPD')),
                ('envio_fpd_critico', models.BooleanField(default=False, verbose_name='FPD crítico (global)')),
                ('envio_churn', models.BooleanField(default=True, verbose_name='Churn')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios_gestao', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Destinatário WhatsApp',
                'verbose_name_plural': 'Destinatários WhatsApp',
                'ordering': ['prioridade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EnvioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('capilaridade', 'Capilaridade'), ('osab', 'OSAB'), ('fpd', 'FPD'), ('fpd_critico', 'FPD crítico'), ('churn', 'Churn'), ('resumo', 'Resumo geral'), ('teste', 'Teste SyncWA')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado (fila SyncWA)'), ('erro', 'Erro'), ('ignorado', 'Ignorado')], db_index=True, default='pendente', max_length=20)),
                ('destino_jid', models.CharField(max_length=80)),
                ('destino_nome', models.CharField(blank=True, max_length=150)),
                ('mensagem', models.TextField()),
                ('modo_teste', models.BooleanField(default=False)),
                ('syncwa_message_id', models.CharField(blank=True, max_length=80)),
                ('syncwa_status', models.CharField(blank=True, max_length=40)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_gestao', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='gestao.destinatario')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_whatsapp', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Envio WhatsApp',
                'verbose_name_plural': 'Envios WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
    ]
