# Generated by Django 5.2.1 on 2026-08-21 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_segunda_onda_whatsapp'),
        ('tickets', '0013_isolar_auth_do_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='envio_comissionamento',
            field=models.BooleanField(default=False, verbose_name='Comissionamento'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='razoes_sociais_comissionamento',
            field=models.TextField(blank=True, help_text='Uma por linha (ou separadas por ;). Filtra as abas PEDIDO / LINHA_A_LINHA.', verbose_name='Razões sociais (comissionamento)'),
        ),
        migrations.AlterField(
            model_name='enviowhatsapp',
            name='tipo',
            field=models.CharField(choices=[('capilaridade', 'Capilaridade'), ('osab', 'OSAB'), ('fpd', 'FPD'), ('fpd_critico', 'FPD crítico'), ('churn', 'Churn'), ('comissionamento', 'Comissionamento'), ('resumo', 'Resumo geral'), ('teste', 'Teste SyncWA')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='loteimportacao',
            name='tipo',
            field=models.CharField(choices=[('sysmap', 'Sysmap / Supply'), ('osab', 'OSAB'), ('fpd', 'FPD'), ('churn', 'Churn'), ('comissionamento', 'Comissionamento')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RelatorioComissionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdv_nome', models.CharField(max_length=150)),
                ('qtd_pedido', models.IntegerField(default=0)),
                ('qtd_linha', models.IntegerField(default=0)),
                ('total_pedido', models.FloatField(default=0)),
                ('total_comissao', models.FloatField(default=0)),
                ('mensagem', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, upload_to='gestao/comissionamento/%Y/%m/')),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_comissionamento', to='gestao.loteimportacao')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_comissionamento', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Relatório de comissionamento',
                'verbose_name_plural': 'Relatórios de comissionamento',
                'ordering': ['-criado_em', 'pdv_nome'],
            },
        ),
    ]
