# Generated by Django 5.2.1 on 2026-08-21 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_quarta_quinta_onda_tarefas_vi'),
        ('tickets', '0013_isolar_auth_do_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='envio_recompra',
            field=models.BooleanField(default=False, verbose_name='Recompra'),
        ),
        migrations.AlterField(
            model_name='enviowhatsapp',
            name='tipo',
            field=models.CharField(choices=[('capilaridade', 'Capilaridade'), ('osab', 'OSAB'), ('fpd', 'FPD'), ('fpd_critico', 'FPD crítico'), ('churn', 'Churn'), ('comissionamento', 'Comissionamento'), ('tarefas', 'Tarefas'), ('venda_indevida', 'Venda indevida'), ('recompra', 'Recompra'), ('resumo', 'Resumo geral'), ('teste', 'Teste SyncWA')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='loteimportacao',
            name='tipo',
            field=models.CharField(choices=[('sysmap', 'Sysmap / Supply'), ('osab', 'OSAB'), ('fpd', 'FPD'), ('churn', 'Churn'), ('comissionamento', 'Comissionamento'), ('tarefas', 'Tarefas'), ('venda_indevida', 'Venda indevida'), ('recompra', 'Recompra')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RelatorioRecompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdv_nome', models.CharField(blank=True, max_length=150)),
                ('total', models.IntegerField(default=0)),
                ('consolidado', models.BooleanField(default=False)),
                ('data_referencia', models.DateField()),
                ('mensagem', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, upload_to='gestao/recompra/%Y/%m/')),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_recompra', to='gestao.loteimportacao')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_recompra', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Relatório de recompra',
                'verbose_name_plural': 'Relatórios de recompra',
                'ordering': ['-criado_em', 'pdv_nome'],
            },
        ),
    ]
