# Generated by Django 5.2.1 on 2026-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_sexta_onda_recompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='email',
            field=models.EmailField(blank=True, help_text='Se preenchido e a máscara estiver marcada abaixo, o envio também vai por e-mail.', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='email_capilaridade',
            field=models.BooleanField(default=False, verbose_name='E-mail Capilaridade'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='email_churn',
            field=models.BooleanField(default=False, verbose_name='E-mail Churn'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='email_comissionamento',
            field=models.BooleanField(default=False, verbose_name='E-mail Comissionamento'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='email_fpd',
            field=models.BooleanField(default=False, verbose_name='E-mail FPD'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='email_fpd_critico',
            field=models.BooleanField(default=False, verbose_name='E-mail FPD crítico'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='email_osab',
            field=models.BooleanField(default=False, verbose_name='E-mail OSAB'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='email_recompra',
            field=models.BooleanField(default=False, verbose_name='E-mail Recompra'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='email_tarefas',
            field=models.BooleanField(default=False, verbose_name='E-mail Tarefas'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='email_venda_indevida',
            field=models.BooleanField(default=False, verbose_name='E-mail Venda indevida'),
        ),
    ]
