# Generated by Django 5.2.1 on 2026-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_email_gestao_e_mascaras'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaosab',
            name='nm_gc',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Nome do GC (OSAB)'),
        ),
    ]
