# Generated by Django 5.2.1 on 2026-09-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0018_atualizar_email_especialista_comissionamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='razoes_sociais_comissionamento',
            field=models.TextField(blank=True, help_text='Legado: razões extras além do cadastro em Parceiros. Prefira cadastrar a razão social na aba Parceiros.', verbose_name='Razões sociais (comissionamento)'),
        ),
        migrations.AlterField(
            model_name='enviowhatsapp',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro'), ('ignorado', 'Ignorado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='enviowhatsapp',
            name='tipo',
            field=models.CharField(choices=[('capilaridade', 'Capilaridade'), ('osab', 'OSAB'), ('fpd', 'FPD'), ('fpd_critico', 'FPD crítico'), ('churn', 'Churn'), ('comissionamento', 'Comissionamento'), ('tarefas', 'Tarefas'), ('venda_indevida', 'Venda indevida'), ('recompra', 'Recompra'), ('parcial', 'Parcial de vendas'), ('acumulado', 'Acumulado do mês'), ('ranking', 'Ranking VB'), ('resumo', 'Resumo geral'), ('teste', 'Teste WhatsApp')], db_index=True, max_length=30),
        ),
    ]
