# Generated by Django 5.2.1 on 2026-09-19 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0027_loteimportacao_gerencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFPDCidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=150)),
                ('indicador', models.CharField(choices=[('FPD', 'FPD'), ('SPD', 'SPD'), ('TPD', 'TPD')], db_index=True, default='FPD', max_length=8)),
                ('segmento', models.CharField(choices=[('todos', 'Todos'), ('varejo', 'Varejo'), ('empresarial', 'Empresarial')], db_index=True, default='todos', max_length=16)),
                ('percentual', models.FloatField()),
                ('total_faturas', models.IntegerField()),
                ('total_abertas', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_fpd_cidade', to='gestao.loteimportacao')),
            ],
            options={
                'verbose_name': 'Relatório FPD Cidade',
                'verbose_name_plural': 'Relatórios FPD Cidade',
                'ordering': ['-percentual', 'cidade'],
                'indexes': [models.Index(fields=['cidade', 'indicador', 'segmento'], name='gestao_rela_cidade_240baf_idx')],
            },
        ),
    ]
