# Generated by Django 5.2.1 on 2026-09-20 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0028_relatoriofpdcidade'),
        ('tickets', '0035_elite_mascara_titular_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriofpdcidade',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_fpd_cidade', to='tickets.parceiro'),
        ),
    ]
