# Generated by Django 5.2.1 on 2026-09-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0029_relatoriofpdcidade_parceiro'),
        ('tickets', '0035_elite_mascara_titular_cpf'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='relatoriofpdcidade',
            name='gestao_rela_cidade_240baf_idx',
        ),
        migrations.AddField(
            model_name='relatoriofpdcidade',
            name='mes',
            field=models.CharField(db_index=True, default='', max_length=6),
        ),
        migrations.AddIndex(
            model_name='relatoriofpdcidade',
            index=models.Index(fields=['cidade', 'mes', 'indicador', 'segmento'], name='gestao_rela_cidade_545a67_idx'),
        ),
    ]
