# Generated by Django 5.2.1 on 2026-09-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0030_remove_relatoriofpdcidade_gestao_rela_cidade_240baf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='ranking_consolidado',
            field=models.BooleanField(default=False, help_text='Marque se este for um grupo geral da carteira (sem PDV fixo). Ele ficará disponível no select de envio na tela de Resultados.', verbose_name='Grupo Consolidado / Resultados da Carteira'),
        ),
    ]
