# Generated by Django 5.2.17 on 2026-08-10 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('destino', models.CharField(help_text='Ex.: Grupo Elite, BO Agendamento, Suporte App', max_length=120)),
                ('tipos', models.CharField(blank=True, help_text='Códigos de tipo separados por vírgula; vazio = todos.', max_length=255)),
                ('template', models.TextField(help_text='Variáveis: {{protocolo}} {{parceiro}} {{pdv}} {{tipo}} {{pedido}} {{documento}} {{endereco}} {{cep}} {{fachada}} {{data}} {{turno}} {{descricao}} {{observacoes}} {{solicitante}} {{contato}} {{tt}} {{os}}')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Máscara',
                'verbose_name_plural': 'Máscaras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pdv', models.CharField(max_length=32, unique=True, verbose_name='Código PDV')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('contato_nome', models.CharField(blank=True, max_length=120, verbose_name='Contato')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('token_acesso', models.CharField(blank=True, help_text='Token opcional para abertura de demanda pelo parceiro sem login staff.', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('agendar_reagendar', 'Agendar/Reagendar pedido (7095, 7029, 7037)'), ('endereco_doc', 'Endereço do CPF/CNPJ'), ('status_pedido', 'Status do pedido - agendamento atual'), ('prioridade_elite', 'Prioridade na instalação (Grupo Elite)'), ('reset_senha', 'Reset de senha'), ('viabilidade', 'Consulta de viabilidade (sistema fora)'), ('acesso_app', 'Chamado acesso App NIO'), ('outros', 'Outros / suporte geral')], max_length=40)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em análise'), ('aguardando_parceiro', 'Aguardando parceiro'), ('encaminhado', 'Encaminhado'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], db_index=True, default='novo', max_length=30)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('solicitante_nome', models.CharField(blank=True, max_length=120, verbose_name='Quem solicita')),
                ('solicitante_contato', models.CharField(blank=True, max_length=60, verbose_name='Telefone/WhatsApp')),
                ('pedido', models.CharField(blank=True, max_length=80, verbose_name='Pedido / OS')),
                ('pedidos_extras', models.TextField(blank=True, help_text='Um por linha — melhoria vs Forms (só 1 pedido).', verbose_name='Pedidos adicionais')),
                ('documento_cliente', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('tt', models.CharField(blank=True, max_length=80, verbose_name='TT')),
                ('cep', models.CharField(blank=True, max_length=12, verbose_name='CEP')),
                ('numero_fachada', models.CharField(blank=True, max_length=40, verbose_name='Nº fachada')),
                ('endereco_completo', models.CharField(blank=True, max_length=255, verbose_name='Endereço completo')),
                ('data_desejada', models.DateField(blank=True, null=True, verbose_name='Data desejada')),
                ('turno', models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('integral', 'Integral / indiferente')], max_length=20)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição detalhada')),
                ('observacoes', models.TextField(blank=True)),
                ('resposta_publica', models.TextField(blank=True, verbose_name='Resposta ao parceiro')),
                ('nota_interna', models.TextField(blank=True, verbose_name='Nota interna')),
                ('destino_encaminhamento', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('primeiro_atendimento_em', models.DateTimeField(blank=True, null=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atendidos', to=settings.AUTH_USER_MODEL)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.parceiro')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nome', models.CharField(blank=True, max_length=120)),
                ('interno', models.BooleanField(default=False, help_text='Se marcado, não aparece para o parceiro.')),
                ('corpo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='tickets.ticket')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=120)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mascara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.mascara')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/%Y/%m/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tickets.ticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-criado_em'], name='tickets_tic_status_994c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tipo', 'status'], name='tickets_tic_tipo_411d5b_idx'),
        ),
    ]
