# Generated by Django 5.2.17 on 2026-08-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resultado_status',
            field=models.CharField(blank=True, db_index=True, help_text='Resumo operacional (ex.: SOLICITADA PRIORIDADE, AGENDAMENTO CANCELADO...).', max_length=255, verbose_name='STATUS'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nota_interna',
            field=models.TextField(blank=True, help_text='Detalhes internos de acompanhamento (não necessariamente público).', verbose_name='DETALHES'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resposta_publica',
            field=models.TextField(blank=True, help_text='Texto de retorno ao parceiro / registro do que foi feito.', verbose_name='RETORNO'),
        ),
    ]
