# Generated by Django 5.2.17 on 2026-08-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_status_retorno_detalhes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='complemento',
            field=models.CharField(blank=True, max_length=80, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='logradouro',
            field=models.CharField(blank=True, max_length=180, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='endereco_completo',
            field=models.CharField(blank=True, help_text='Montado automaticamente pelo ViaCEP + nº/complemento.', max_length=255, verbose_name='Endereço completo'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('agendar_reagendar', 'Agendar/Reagendar pedido (7095, 7029, 7037)'), ('endereco_doc', 'Endereço do CPF/CNPJ'), ('status_pedido', 'Status do pedido - agendamento atual'), ('prioridade_elite', 'Prioridade na instalação (Grupo Elite)'), ('reset_senha', 'Reset de senha'), ('viabilidade', 'Consulta de viabilidade (sistema fora)'), ('acesso_app', 'Chamado acesso App NIO'), ('abrir_chamado_ti', 'Abrir chamado com TI'), ('sem_slot', 'Sinalização — sem slot / liberação de agenda'), ('instalacao_fisica', 'Sinalização — instalação física / pendência'), ('outros', 'Outros / suporte geral')], max_length=40),
        ),
    ]
