# Generated by Django 5.2.17 on 2026-08-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_endereco_viacep_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('agendar_reagendar', 'Agendar/Reagendar pedido (7095, 7029, 7037)'), ('endereco_doc', 'Endereço do Pedido'), ('status_pedido', 'Status do pedido - agendamento atual'), ('prioridade_elite', 'Prioridade na instalação (Grupo Elite)'), ('reset_senha', 'Reset de senha'), ('viabilidade', 'Consulta de viabilidade (sistema fora)'), ('acesso_app', 'Chamado acesso App NIO'), ('abrir_chamado_ti', 'Abrir chamado com TI'), ('sem_slot', 'Sinalização — sem slot / liberação de agenda'), ('instalacao_fisica', 'Sinalização — instalação física / pendência'), ('outros', 'Outros / suporte geral')], max_length=40),
        ),
    ]
