# Generated by Django 5.2.17 on 2026-08-10 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_endereco_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='contato_nome',
            field=models.CharField(blank=True, help_text='Preferir cadastro em Contatos do PDV.', max_length=120, verbose_name='Contato principal (legado)'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='token_acesso',
            field=models.CharField(blank=True, help_text='Token geral do PDV (opcional). Contatos podem ter token próprio.', max_length=64),
        ),
        migrations.CreateModel(
            name='ContatoParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp / telefone')),
                ('cargo', models.CharField(blank=True, max_length=80)),
                ('token_acesso', models.CharField(blank=True, help_text='Se preenchido, exige este token ao selecionar o contato.', max_length=64)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Contato do parceiro',
                'verbose_name_plural': 'Contatos do parceiro',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.contatoparceiro', verbose_name='Contato que abriu'),
        ),
        migrations.AddConstraint(
            model_name='contatoparceiro',
            constraint=models.UniqueConstraint(fields=('parceiro', 'nome'), name='uniq_contato_nome_por_parceiro'),
        ),
    ]
