# Generated by Django 5.2.17 on 2026-08-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_contatos_parceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='retorno_dados',
            field=models.JSONField(blank=True, default=dict, help_text='Campos estruturados da resposta (senha, endereço consultado, etc.).', verbose_name='Dados do retorno'),
        ),
    ]
