# Generated by Django 5.2.17 on 2026-08-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_retorno_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tt_backoffice',
            field=models.CharField(blank=True, help_text='TT do backoffice de cadastro do pedido com problema.', max_length=80, verbose_name='TT do backoffice de cadastro'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tt_vendedor',
            field=models.CharField(blank=True, max_length=80, verbose_name='TT do vendedor'),
        ),
        migrations.AlterField(
            model_name='contatoparceiro',
            name='token_acesso',
            field=models.CharField(blank=True, help_text='Legado — o portal usa apenas o token do PDV.', max_length=64),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='token_acesso',
            field=models.CharField(blank=True, help_text='Um único token para todos os contatos deste PDV (opcional).', max_length=64),
        ),
    ]
