# Generated by Django 5.2.17 on 2026-08-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_tt_vendedor_backoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascara',
            name='template',
            field=models.TextField(help_text='Variáveis: {{protocolo}} {{parceiro}} {{pdv}} {{tipo}} {{pedido}} {{documento}} {{endereco}} {{cep}} {{fachada}} {{data}} {{turno}} {{descricao}} {{observacoes}} {{solicitante}} {{contato}} {{tt}} {{tt_vendedor}} {{tt_backoffice}} {{os}}'),
        ),
    ]
