# Generated by Django 5.2.17 on 2026-08-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_mascara_help_tt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRespostaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agendar_reagendar', 'Agendar/Reagendar pedido (7095, 7029, 7037)'), ('endereco_doc', 'Endereço do Pedido'), ('status_pedido', 'Status do pedido - agendamento atual'), ('prioridade_elite', 'Prioridade na instalação (Grupo Elite)'), ('reset_senha', 'Reset de senha'), ('viabilidade', 'Consulta de viabilidade (sistema fora)'), ('acesso_app', 'Chamado acesso App NIO'), ('abrir_chamado_ti', 'Abrir chamado com TI'), ('sem_slot', 'Sinalização — sem slot / liberação de agenda'), ('instalacao_fisica', 'Sinalização — instalação física / pendência'), ('outros', 'Outros / suporte geral')], db_index=True, max_length=40, unique=True)),
                ('campos', models.JSONField(blank=True, default=list, help_text='Lista de campos: name, label, widget, required, ativo, help, placeholder.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config. resposta por tipo',
                'verbose_name_plural': 'Configs resposta por tipo',
                'ordering': ['tipo'],
            },
        ),
    ]
