# Generated by Django 5.2.1 on 2026-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_perfilstaff_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascara',
            name='enviar_email',
            field=models.BooleanField(default=False, help_text='O especialista do PDV recebe esta máscara por e-mail quando a solicitação é registrada.', verbose_name='Enviar por e-mail ao abrir a demanda'),
        ),
    ]
