# Generated by Django 5.2.1 on 2026-08-30 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_parceiro_credenciamento_endereco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VtalDadosViabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linha_planilha', models.IntegerField(blank=True, null=True)),
                ('carimbo_data_hora', models.DateTimeField(blank=True, null=True)),
                ('email_solicitante', models.EmailField(blank=True, max_length=254, null=True)),
                ('executivo_vendas', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_empresa_vendas_planilha', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_protocolo', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula_solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('operacao', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_eps', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_uf', models.TextField(blank=True, null=True)),
                ('cep', models.TextField(blank=True, null=True)),
                ('cep_normalizado', models.CharField(blank=True, max_length=16, null=True)),
                ('cidade', models.TextField(blank=True, null=True)),
                ('tipo_logradouro', models.TextField(blank=True, null=True)),
                ('logradouro', models.TextField(blank=True, null=True)),
                ('numero_fachada', models.TextField(blank=True, null=True)),
                ('fachada_normalizada', models.CharField(blank=True, max_length=64, null=True)),
                ('bairro', models.TextField(blank=True, null=True)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('observacoes_vendas', models.TextField(blank=True, null=True)),
                ('status_tratamento', models.TextField(blank=True, null=True)),
                ('observacoes_vtal', models.TextField(blank=True, null=True)),
                ('data_evento_vtal', models.DateField(blank=True, null=True)),
                ('horario_fechamento_vtal', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'viabilidade_dadosviabilidade',
                'ordering': ['-carimbo_data_hora', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VtalFonteDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('import_last_sheet_row_number', models.IntegerField(default=0)),
                ('import_last_sheet_row_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'viabilidade_fontedados',
                'ordering': ['ordem', 'nome'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='contatoparceiro',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Empresário', 'Empresário'), ('Backoffice', 'Backoffice')], max_length=80),
        ),
        migrations.AlterField(
            model_name='perfilstaff',
            name='papel',
            field=models.CharField(choices=[('gestor', 'Admin'), ('especialista', 'Especialista')], db_index=True, default='especialista', max_length=20),
        ),
        migrations.CreateModel(
            name='ProcessoRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('cadastro', 'Cadastro'), ('viabilidade', 'Viabilidade'), ('financeiro', 'Financeiro / crédito'), ('operacional', 'Operacional'), ('outro', 'Outro')], default='operacional', max_length=32)),
                ('resumo', models.CharField(blank=True, help_text='Texto curto para cards e listagens.', max_length=280)),
                ('finalidade', models.TextField(help_text='Objetivo do processo e quando o parceiro deve usá-lo.', verbose_name='Para que serve?')),
                ('quando_usar', models.TextField(blank=True, help_text='Ex.: tela de erro no PAP, mensagem do sistema, etc.', verbose_name='Quando usar (sinais / gatilhos)')),
                ('encaminhamento', models.TextField(blank=True, help_text='Destino, área responsável ou fila.', verbose_name='Encaminha para quem?')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('demanda', 'Abrir demanda no portal'), ('link', 'Link externo'), ('manual', 'Procedimento manual'), ('misto', 'Misto (e-mail + anexo + outros)')], default='email', max_length=20)),
                ('email_destino', models.EmailField(blank=True, max_length=254, verbose_name='E-mail destino')),
                ('email_cc_especialista', models.BooleanField(default=False, help_text='Inclui o e-mail do especialista NIO vinculado ao parceiro (portal).', verbose_name='Copiar especialista do PDV')),
                ('email_cc_extra', models.CharField(blank=True, help_text='E-mails adicionais separados por vírgula.', max_length=500, verbose_name='CC fixo')),
                ('requer_planilha', models.BooleanField(default=False, verbose_name='Exige planilha / formulário')),
                ('instrucoes_planilha', models.TextField(blank=True, help_text='Como preencher e anexar no e-mail.', verbose_name='Instruções da planilha')),
                ('passos', models.TextField(blank=True, help_text='Um passo por linha. Ex.: 1) Baixar formulário…', verbose_name='Passo a passo')),
                ('tags', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula (busca).', max_length=200)),
                ('publico', models.BooleanField(default=True, verbose_name='Visível no portal parceiro')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo (repositório)',
                'verbose_name_plural': 'Processos (repositório)',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=500)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tickets.processorepositorio')),
            ],
            options={
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('arquivo', models.FileField(upload_to='repositorio/%Y/%m/')),
                ('tipo', models.CharField(choices=[('planilha', 'Planilha / formulário'), ('modelo', 'Modelo / template'), ('evidencia', 'Exemplo / evidência'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tickets.processorepositorio')),
            ],
            options={
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
