# Generated by Django 5.2.1 on 2026-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0020_repositorio_processos"),
    ]

    operations = [
        migrations.CreateModel(
            name="VtalSystemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_end_time", models.DateTimeField(blank=True, null=True)),
                ("import_last_full_sync", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "viabilidade_systemstatus",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="vtalfontedados",
            name="import_last_full_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
