# Generated by Django 5.2.1 on 2026-09-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_vtal_ultima_importacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascara',
            name='enviar_whatsapp',
            field=models.BooleanField(default=False, help_text='O especialista do PDV recebe esta máscara por WhatsApp quando a solicitação é registrada (se não for admin).', verbose_name='Enviar por WhatsApp ao abrir a demanda'),
        ),
    ]
