# Generated by Django 5.2.1 on 2026-09-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0021_alter_enviowhatsapp_tipo'),
        ('tickets', '0022_mascara_enviar_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilstaff',
            name='mascara_grupo',
            field=models.ForeignKey(blank=True, help_text='Grupo de WhatsApp selecionado da lista de Destinatários.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gestao.destinatario'),
        ),
        migrations.AddField(
            model_name='perfilstaff',
            name='mascara_grupo_custom',
            field=models.CharField(blank=True, help_text='JID ou identificador do grupo caso não esteja cadastrado na lista.', max_length=120, verbose_name='JID / nome do grupo'),
        ),
        migrations.AddField(
            model_name='perfilstaff',
            name='mascara_numero',
            field=models.CharField(blank=True, help_text='Número com DDI, só dígitos. Ex.: 5531999999999.', max_length=40, verbose_name='Número individual (WhatsApp)'),
        ),
        migrations.AddField(
            model_name='perfilstaff',
            name='mascara_numero_nome',
            field=models.CharField(blank=True, help_text='Nome ou descrição do contato (opcional).', max_length=120, verbose_name='Nome do contato individual'),
        ),
        migrations.AddField(
            model_name='perfilstaff',
            name='tipo_destino_mascara',
            field=models.CharField(choices=[('proprio', 'Para ele (WhatsApp do especialista)'), ('grupo', 'Para algum grupo de WhatsApp'), ('individual', 'Para um número individual')], default='proprio', help_text='Define para onde vai a máscara gerada para os tickets deste especialista.', max_length=20, verbose_name='Destino da máscara'),
        ),
    ]
