# Generated by Django 5.2.1 on 2026-09-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_perfilstaff_mascara_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoSemanalRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(db_index=True, help_text='Segunda-feira (ISO) da semana de referência.')),
                ('vendas_planejadas', models.PositiveIntegerField()),
                ('meta_referencia', models.PositiveIntegerField(default=0, help_text='Snapshot da meta semanal corporativa no momento do registro.')),
                ('status_alerta', models.CharField(choices=[('ok', 'OK'), ('abaixo', 'Abaixo'), ('critico', 'Crítico')], default='ok', max_length=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_rota', to='tickets.contatoparceiro')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos_rota', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Planejamento semanal (Rota)',
                'verbose_name_plural': 'Planejamentos semanais (Rota)',
                'ordering': ['-semana_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CheckinRotaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('tipo_rota', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('DIGITAL', 'Digital')], max_length=16)),
                ('qtd_vendedores', models.PositiveIntegerField()),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('hp_livres', models.PositiveIntegerField(blank=True, null=True)),
                ('faixa_credito', models.CharField(blank=True, max_length=80)),
                ('alerta_dfv', models.CharField(blank=True, max_length=255)),
                ('dfv_payload', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_rota', to='tickets.contatoparceiro')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_rota', to='tickets.parceiro')),
                ('planejamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='tickets.planejamentosemanalrota')),
            ],
            options={
                'verbose_name': 'Check-in diário (Rota)',
                'verbose_name_plural': 'Check-ins diários (Rota)',
                'ordering': ['-data', '-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParceiroPraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, max_length=2)),
                ('cidade', models.CharField(db_index=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pracas_rota', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Praça do parceiro (Rota)',
                'verbose_name_plural': 'Praças do parceiro (Rota)',
                'ordering': ['uf', 'cidade', 'bairro'],
                'constraints': [models.UniqueConstraint(fields=('parceiro', 'uf', 'cidade', 'bairro'), name='uniq_parceiro_praca_rota')],
            },
        ),
        migrations.AddConstraint(
            model_name='planejamentosemanalrota',
            constraint=models.UniqueConstraint(fields=('parceiro', 'semana_inicio'), name='uniq_planejamento_rota_parceiro_semana'),
        ),
        migrations.AddConstraint(
            model_name='checkinrotadiaria',
            constraint=models.UniqueConstraint(fields=('parceiro', 'data'), name='uniq_checkin_rota_parceiro_data'),
        ),
    ]
