# Generated by Django 5.2.1 on 2026-09-15 22:34

from django.db import migrations, models

TIPOS_KIT = (
    "pendencia_indevida,agenda_nao_cumprida,slot_alongado,"
    "reagendamento_nao_solicitado,agendamento_cancelado,"
    "cancelamento_reemissao_indevida,os_nao_atribuida"
)

MASCARAS_NOVAS = [
    {
        "nome": "Kit operação — OS / pendência / agenda",
        "destino": "Esteira / Operação",
        "tipos": TIPOS_KIT,
        "template": (
            "*{{tipo}}*\n\n"
            "- *OS:* {{os}}\n"
            "- *SA:* {{sa}}\n"
            "- *CLIENTE:* {{nome_cliente}}\n"
            "- *CONTATO:* {{solicitante}}\n"
            "- *TELEFONE:* {{contato}}\n"
            "- *CIDADE:* {{cidade}}\n"
            "- *ENDEREÇO:* {{endereco}}\n"
            "- *DATA:* {{data}}\n"
            "- *TIPO DA PENDÊNCIA:* {{tipo_pendencia}}\n"
            "- *RECORRÊNCIA:* {{recorrencia}}\n"
            "- *DETALHAMENTO:* {{descricao}}\n"
            "- *PDV:* {{pdv}} - {{parceiro}}\n"
        ),
    },
    {
        "nome": "Vazamento de dados",
        "destino": "Segurança / LGPD",
        "tipos": "vazamento_dados",
        "template": (
            "*VAZAMENTO DE DADOS*\n"
            "Protocolo: {{protocolo}}\n"
            "PDV: {{pdv}} — {{parceiro}}\n"
            "CPF/CNPJ: {{documento}}\n"
            "OS: {{os}}\n"
            "Data da ocorrência: {{data}}\n"
            "Situação: {{descricao}}\n"
        ),
    },
    {
        "nome": "Apoio gestão de acessos",
        "destino": "Gestão de acessos",
        "tipos": "gestao_acessos",
        "template": (
            "*APOIO GESTÃO DE ACESSOS*\n"
            "Protocolo: {{protocolo}}\n"
            "PDV: {{pdv}} — {{parceiro}}\n"
            "TT: {{tt}}\n"
            "Cargo: {{cargo}}\n"
            "Nome: {{solicitante}}\n"
            "CPF/CNPJ: {{documento}}\n"
            "RG: {{rg}}\n"
            "E-mail: {{email}}\n"
            "Detalhe: {{descricao}}\n"
        ),
    },
]

TEMPLATE_SEM_SLOT = (
    "Sem SLOT em {{uf}}\n\n"
    "Situação: {{variacao_sem_slot}}\n"
    "Pedido: {{pedido}}\n"
    "Endereço: {{endereco}}\n"
    "Data e turno: {{data}} - {{turno}}\n"
    "Data D+1 sem slot: {{data_2}}\n"
    "Tel. de contato: {{contato}}\n"
)

TEMPLATE_ORIENTACOES = (
    "*ORIENTAÇÕES DE PENDÊNCIAS*\n"
    "Protocolo: {{protocolo}}\n"
    "PDV: {{pdv}} — {{parceiro}}\n"
    "Pedido(s):\n{{pedidos}}\n"
    "CPF: {{documento}}\n"
    "Data desejada: {{data}} | Turno: {{turno}}\n"
    "Contato: {{solicitante}} / {{contato}}\n"
    "Obs: {{observacoes}}\n"
)


def atualizar_mascaras(apps, schema_editor):
    Mascara = apps.get_model("tickets", "Mascara")
    Mascara.objects.filter(tipos="sem_slot").update(template=TEMPLATE_SEM_SLOT)
    Mascara.objects.filter(tipos="agendar_reagendar").update(template=TEMPLATE_ORIENTACOES)
    for data in MASCARAS_NOVAS:
        Mascara.objects.update_or_create(
            nome=data["nome"],
            defaults={
                "destino": data["destino"],
                "tipos": data["tipos"],
                "template": data["template"],
                "ativo": True,
            },
        )


def reverter_mascaras(apps, schema_editor):
    Mascara = apps.get_model("tickets", "Mascara")
    Mascara.objects.filter(
        nome__in=[item["nome"] for item in MASCARAS_NOVAS]
    ).delete()


class Migration(migrations.Migration):


    dependencies = [
        ('tickets', '0025_elite_mascara_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cargo_acesso',
            field=models.CharField(blank=True, max_length=80, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email_solicitante',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='recorrencia',
            field=models.CharField(blank=True, choices=[('nao', 'Não'), ('sim', 'Sim')], max_length=10, verbose_name='Recorrência'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rg',
            field=models.CharField(blank=True, max_length=30, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sa',
            field=models.CharField(blank=True, max_length=80, verbose_name='SA'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_pendencia',
            field=models.CharField(blank=True, max_length=80, verbose_name='Tipo da pendência'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='variacao_sem_slot',
            field=models.CharField(blank=True, choices=[('sem_agenda', 'Pedido sem slot para agendar'), ('agendado_d1', 'Já agendado — sem slot D+1')], max_length=20, verbose_name='Situação do pedido'),
        ),
        migrations.AlterField(
            model_name='configrespostatipo',
            name='tipo',
            field=models.CharField(choices=[('agendar_reagendar', 'Orientações de pendências'), ('endereco_doc', 'Endereço do Pedido'), ('status_pedido', 'Status do pedido - agendamento atual'), ('prioridade_elite', 'Prioridade na instalação (Grupo Elite)'), ('reset_senha', 'Reset de senha'), ('viabilidade', 'Consulta de viabilidade (sistema fora)'), ('acesso_app', 'Chamado acesso App NIO'), ('abrir_chamado_ti', 'Abrir chamado com TI'), ('sem_slot', 'Sinalização — sem slot / liberação de agenda'), ('instalacao_fisica', 'Sinalização — instalação física / pendência'), ('reparo', 'Reparo — internet pós-instalação (até 14 dias)'), ('pendencia_indevida', 'Pendência indevida'), ('agenda_nao_cumprida', 'Agenda não cumprida'), ('slot_alongado', 'Slot alongado'), ('reagendamento_nao_solicitado', 'Reagendamento não solicitado'), ('agendamento_cancelado', 'Agendamento cancelado'), ('cancelamento_reemissao_indevida', 'Cancelamento/reemissão indevida'), ('os_nao_atribuida', 'OS não atribuída'), ('vazamento_dados', 'Vazamento de dados'), ('gestao_acessos', 'Apoio gestão de acessos'), ('outros', 'Outros / suporte geral')], db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='mascara',
            name='template',
            field=models.TextField(help_text='Variáveis: {{protocolo}} {{parceiro}} {{pdv}} {{tipo}} {{pedido}} {{documento}} {{endereco}} {{cep}} {{fachada}} {{data}} {{turno}} {{data_2}} {{turno_2}} {{nome_cliente}} {{data_instalacao}} {{nome_gc}} {{descricao}} {{observacoes}} {{solicitante}} {{contato}} {{tt}} {{tt_vendedor}} {{tt_backoffice}} {{os}} {{sa}} {{tipo_pendencia}} {{recorrencia}} {{variacao_sem_slot}} {{cargo}} {{rg}} {{email}}'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('agendar_reagendar', 'Orientações de pendências'), ('endereco_doc', 'Endereço do Pedido'), ('status_pedido', 'Status do pedido - agendamento atual'), ('prioridade_elite', 'Prioridade na instalação (Grupo Elite)'), ('reset_senha', 'Reset de senha'), ('viabilidade', 'Consulta de viabilidade (sistema fora)'), ('acesso_app', 'Chamado acesso App NIO'), ('abrir_chamado_ti', 'Abrir chamado com TI'), ('sem_slot', 'Sinalização — sem slot / liberação de agenda'), ('instalacao_fisica', 'Sinalização — instalação física / pendência'), ('reparo', 'Reparo — internet pós-instalação (até 14 dias)'), ('pendencia_indevida', 'Pendência indevida'), ('agenda_nao_cumprida', 'Agenda não cumprida'), ('slot_alongado', 'Slot alongado'), ('reagendamento_nao_solicitado', 'Reagendamento não solicitado'), ('agendamento_cancelado', 'Agendamento cancelado'), ('cancelamento_reemissao_indevida', 'Cancelamento/reemissão indevida'), ('os_nao_atribuida', 'OS não atribuída'), ('vazamento_dados', 'Vazamento de dados'), ('gestao_acessos', 'Apoio gestão de acessos'), ('outros', 'Outros / suporte geral')], max_length=40),
        ),
        migrations.RunPython(atualizar_mascaras, reverter_mascaras),
    ]
