# Generated by Django 5.2.1 on 2026-09-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0026_matriz_operacao_demandas"),
    ]

    operations = [
        migrations.AddField(
            model_name="parceiro",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                help_text="Usuário Django deste PDV. O login é o código do PDV.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parceiro_conta",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Conta de login",
            ),
        ),
        migrations.AlterField(
            model_name="parceiro",
            name="token_acesso",
            field=models.CharField(
                blank=True,
                help_text="Legado. Na migração vira senha hasheada; não use mais no portal.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="contatoparceiro",
            name="token_acesso",
            field=models.CharField(
                blank=True,
                help_text="Legado — o portal usa apenas o token do PDV.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="perfilstaff",
            name="papel",
            field=models.CharField(
                choices=[
                    ("gestor", "Admin"),
                    ("gerencia", "Gerência"),
                    ("especialista", "Especialista"),
                ],
                db_index=True,
                default="especialista",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ContaAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("must_change_password", models.BooleanField(default=False)),
                ("password_alterado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "mfa_obrigatorio",
                    models.BooleanField(
                        default=False,
                        help_text="Reservado: TOTP para Admin/Gerência (não ativo nesta entrega).",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conta_acesso",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta de acesso",
                "verbose_name_plural": "Contas de acesso",
            },
        ),
        migrations.CreateModel(
            name="RegistroAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("login_ok", "Login"),
                            ("login_falha", "Falha de login"),
                            ("reset", "Reset de senha"),
                            ("troca", "Troca de senha"),
                            ("troca_obrigatoria", "Troca obrigatória"),
                            ("inativacao", "Inativação"),
                            ("reativacao", "Reativação"),
                            ("bloqueio", "Bloqueio por tentativas"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("username_tentativa", models.CharField(blank=True, max_length=150)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("detalhe", models.CharField(blank=True, max_length=250)),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "alvo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_acesso_recebidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_acesso_feitos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de acesso",
                "verbose_name_plural": "Registros de acesso",
                "ordering": ["-criado_em"],
            },
        ),
    ]
