# Generated by Django 5.2.1 on 2026-09-16 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0027_login_unificado"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinrotadiaria",
            name="qtd_equipes",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="checkinrotadiaria",
            name="equipes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="checkinrotadiaria",
            name="qtd_contratacoes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkinrotadiaria",
            name="qtd_desligamentos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkinrotadiaria",
            name="criado_por_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkins_rota_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="checkinrotadiaria",
            name="tipo_rota",
            field=models.CharField(
                choices=[
                    ("PRESENCIAL", "Presencial"),
                    ("PAP", "PAP"),
                    ("DIGITAL", "Digital"),
                    ("MISTO", "Misto"),
                ],
                max_length=16,
            ),
        ),
    ]
