# Generated by Django 5.2.1 on 2026-09-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0028_rota_equipes_semana"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinrotadiaria",
            name="planejamento_vb_dia",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Planejamento absoluto de VBs do dia.",
            ),
        ),
    ]
