# Generated by Django 5.2.1 on 2026-09-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0029_rota_planejamento_vb_dia"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinrotadiaria",
            name="horario_inicio",
            field=models.TimeField(
                blank=True,
                help_text="Horário de começo da rota.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkinrotadiaria",
            name="horario_fim",
            field=models.TimeField(
                blank=True,
                help_text="Horário final da rota.",
                null=True,
            ),
        ),
    ]
