# Generated by Django 5.2.1 on 2026-09-16 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_rota_horario_inicio_fim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoVertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_condominio', models.CharField(max_length=255)),
                ('nome_sindico', models.CharField(max_length=255)),
                ('contato_sindico', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('infraestrutura_tipo', models.CharField(choices=[('SUBTERRANEA', 'Subterrânea'), ('AEREA', 'Aérea (Poste)'), ('MISTA', 'Mista')], default='SUBTERRANEA', max_length=50)),
                ('possui_shaft_dg', models.BooleanField(default=False)),
                ('total_hps', models.IntegerField(default=0)),
                ('pre_venda_minima', models.IntegerField(default=0)),
                ('arquivo_carta', models.FileField(blank=True, upload_to='vertical/carta/%Y/%m/')),
                ('arquivo_fachada', models.FileField(blank=True, upload_to='vertical/fachada/%Y/%m/')),
                ('destinatarios_resumo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SEM_TRATAMENTO', 'Sem tratamento'), ('EM_CADASTRO', 'Em cadastro'), ('EM_PROJETO', 'Em Projeto'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('ARQUIVADA', 'Arquivada')], db_index=True, default='SEM_TRATAMENTO', max_length=50)),
                ('observacao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_vertical', to=settings.AUTH_USER_MODEL)),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_vertical', to='tickets.parceiro')),
            ],
            options={
                'verbose_name': 'Solicitação Projeto Vertical',
                'verbose_name_plural': 'Solicitações Projeto Vertical',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='BlocoVertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bloco', models.CharField(max_length=100)),
                ('andares', models.IntegerField()),
                ('unidades_por_andar', models.IntegerField()),
                ('total_hps_bloco', models.IntegerField()),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='tickets.solicitacaovertical')),
            ],
            options={
                'verbose_name': 'Bloco (Projeto Vertical)',
                'verbose_name_plural': 'Blocos (Projeto Vertical)',
                'ordering': ['nome_bloco'],
            },
        ),
    ]
