# Generated by Django 5.2.1 on 2026-09-16 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0031_projeto_vertical"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaovertical",
            name="contato",
            field=models.ForeignKey(
                blank=True,
                help_text="Contato do PDV que estava logado no portal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitacoes_vertical",
                to="tickets.contatoparceiro",
            ),
        ),
    ]
