# Generated by Django 5.2.1 on 2026-09-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0032_solicitacao_vertical_contato"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinrotadiaria",
            name="mesma_rota",
            field=models.BooleanField(
                default=True,
                help_text="Várias equipes PAP/mistas no mesmo UF/cidade/bairro.",
            ),
        ),
        migrations.AddField(
            model_name="checkinrotadiaria",
            name="dividir_bairros",
            field=models.BooleanField(
                default=False,
                help_text="Uma equipe PAP/mista atuando em mais de um bairro no dia.",
            ),
        ),
    ]
