# Generated by Django 5.2.1 on 2026-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_elite_mascara_titular_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaPendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quando_acontece', models.TextField(blank=True, verbose_name='Quando acontece')),
                ('esteira', models.CharField(blank=True, max_length=100, verbose_name='Esteira')),
                ('agendavel', models.CharField(blank=True, max_length=50, verbose_name='Pendência Agendável')),
                ('elegivel_mem_crv', models.CharField(blank=True, max_length=50, verbose_name='Elegível ao MEM CRV?')),
                ('elegivel_pav', models.CharField(blank=True, max_length=50, verbose_name='Elegível a PAV (PA Virtual)?')),
                ('tratamento_humano_discador', models.CharField(blank=True, max_length=50, verbose_name='Elegível ao tratamento humano (discador|preview)')),
                ('tratamento_humano_whatsapp', models.CharField(blank=True, max_length=50, verbose_name='Elegível ao tratamento Humano (whatsapp)')),
                ('nota', models.TextField(blank=True, verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Guia de Pendência',
                'verbose_name_plural': 'Guias de Pendência',
                'ordering': ['codigo', 'descricao'],
            },
        ),
    ]
